version: "3.8"

services:
  app:
    build:
      context: .
    container_name: password-generator
    ports:
      - "5050:5050"  # Optional if you only want access via NGINX
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "90:90"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
